[workspace]
resolver = "2"
members = [
    "lib/shared",
    "lib/ml",

    "tools/bin2mem",

    "examples/ml-xor",
    "examples/ml-mnist",

    "soc/firmware-test",

    "demo/raymed/packages/classifier",
]
