services:
  postgres:
    container_name: raymed-postgres
    image: postgres
    environment:
      - POSTGRES_USER=raymed
      - POSTGRES_PASSWORD=demyar
      - POSTGRES_DB=raymeddb
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
